Add quote
mcpt/wlmoj pull request #62
Opened 2020-12-30 23:21 UTC by MstrPikachu

2020-12-30 23:22 UTC, 0ffz requested changes

2020-12-30 23:22 UTC, 0ffz commented on resources/quotes.json
> +    "quote": ":hudab:"
Comma!

2020-12-30 23:31 UTC, 0ffz approved these changes

2020-12-31 01:20 UTC, fluix-dev commented on resources/quotes.json
> +    "tooltip": null
```suggestion
    "tooltip": ":hudabbutbetter:"
```

2020-12-31 06:19 UTC, merged